// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSFLrcKziAptVFRtMij0JTBwm-RboB9Hc',
    appId: '1:400586110924:web:7391835d8a89900e818f69',
    messagingSenderId: '400586110924',
    projectId: 'newsflow-8a8c4',
    authDomain: 'newsflow-8a8c4.firebaseapp.com',
    storageBucket: 'newsflow-8a8c4.appspot.com',
    measurementId: 'G-EQGNF5JQWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEKHc2Qm7IQm8uSiMGRaIMkVUlIhw6Kj0',
    appId: '1:400586110924:android:62b6f28bcd16f595818f69',
    messagingSenderId: '400586110924',
    projectId: 'newsflow-8a8c4',
    storageBucket: 'newsflow-8a8c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCofWdEkyxmebP7mSORZlCkvxuqV_R1T0k',
    appId: '1:400586110924:ios:7191bc55fa5fa84a818f69',
    messagingSenderId: '400586110924',
    projectId: 'newsflow-8a8c4',
    storageBucket: 'newsflow-8a8c4.appspot.com',
    iosClientId: '400586110924-gb8lfmo6cb1sqamg4o1u10f9jj8qg2ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCofWdEkyxmebP7mSORZlCkvxuqV_R1T0k',
    appId: '1:400586110924:ios:7191bc55fa5fa84a818f69',
    messagingSenderId: '400586110924',
    projectId: 'newsflow-8a8c4',
    storageBucket: 'newsflow-8a8c4.appspot.com',
    iosClientId: '400586110924-gb8lfmo6cb1sqamg4o1u10f9jj8qg2ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsflow',
  );
}
